language: java
before_install:
  - export PATH="/tmp/bin:$HOME/bin:$PATH"
install:
  - mkdir -p /tmp/bin && cd /tmp/bin
  - wget https://github.com/whudoc/statics/raw/master/linuxbin/qrsync
  - chmod +x qrsync
  - cd ~/build/district10/md2html;
script:
  - mvn package && mkdir publish && cp target md2html.jar publish/ && cat conf.json.in | sed -e "s/QiNiuAK/$QiNiuAK/" | sed -e "s/QiNiuSK/$QiNiuSK/" > conf.json && qrsync conf.json
