sudo: required
language: java
jdk:
  - oraclejdk8
before_install:
  - export PATH="/tmp/bin:$HOME/bin:$PATH"
  - export PANDOC_URL="https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb"
  - export QRSYNC_URL="https://github.com/whudoc/statics/raw/master/linuxbin/qrsync"
install:
  - mkdir -p /tmp/bin && cd /tmp/bin
  - wget $QRSYNC_URL && chmod +x qrsync
  - wget $PANDOC_URL && sudo dpkg -i pandoc*.deb
script:
  - cd ~/build/district10/md2html;
  - mvn -v
  - make
  - make test test1 test2 && qrsync <(cat conf.json.in | sed -e "s/QiNiuAK/$QiNiuAK/" | sed -e "s/QiNiuSK/$QiNiuSK/")
